version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    container_name: my-jenkins-3
    volumes:
      - /opt/jenkins/jenkins-new:/var/jenkins_home
