version: "3"
services:
  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: sonarquberry@12
    volumes:
      - /opt/sonarqube/sonarqube/data:/opt/sonarqube/data
      - /opt/sonarqube/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/sonarqube/sonarqube/logs:/opt/sonarqube/logs
      - /opt/sonarqube/sonarqube/conf:/opt/sonarqube/conf
    ports:
      - "9000:9000"
  db:
    image: postgres:11.15
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sonarquberry@12
      POSTGRES_DB: sonar
    volumes:
      - /opt/sonarqube/postgress:/var/lib/postgresql/data
